{{- if .Values.certmanager.enable }}
# Self-signed Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: selfsigned-issuer
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selfSigned: {}
{{- if .Values.metrics.enable }}
---
# Certificate for the metrics
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    {{- if .Values.crd.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: metrics-certs
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  dnsNames:
    - ingressnetworkpolicy-operator.{{ .Values.namespace | default .Release.Namespace }}.svc
    - ingressnetworkpolicy-operator.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local
    - ingressnetworkpolicy-operator-metrics-service.{{ .Values.namespace | default .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: metrics-server-cert
{{- end }}
{{- end }}
