# This rule is not used by the project ingressnetworkpolicy-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ingressnetworkpolicies.vitistack.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ingressnetworkpolicy-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicy-viewer-role
rules:
- apiGroups:
  - ingressnetworkpolicies.vitistack.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingressnetworkpolicies.vitistack.io
  resources:
  - networkpolicies/status
  verbs:
  - get
