---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ingressnetworkpolicies.vitistack.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ingressnetworkpolicies.vitistack.io
  resources:
  - ingresses/finalizers
  - networkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - ingressnetworkpolicies.vitistack.io
  resources:
  - ingresses/status
  - networkpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ingressnetworkpolicies.vitistack.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
