{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: ingressnetworkpolicy-operator-manager-role
rules:
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  - networkpolicies/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies/finalizers
  verbs:
  - list
  - watch
{{- end -}}
